version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  api:
    restart: on-failure:5
    image: naturalis/museumapp_pipeline_api:latest
    environment:
      - API_USER=${API_USER}
      - API_PASS=${API_PASS}
      - API_USERID=${API_USERID}
      - JWT_KEY=${JWT_KEY}
      - ES_PORT=${ES_PORT}
      - ES_HOST=${ES_HOST}
      - ES_INDEX=${ES_INDEX}
      - ES_CONTROL_INDEX=${ES_CONTROL_INDEX}
      - LOGFILE_PATH=${API_LOGFILE_PATH}
      - DEBUGGING=${API_DEBUGGING:-0}
    ports:
      - 5000:5000
    volumes:
      - /data:/data
    links:
      - elastic:elastic

  elastic:
    restart: on-failure:5
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - /data/es-data:/usr/share/elasticsearch/data

  elastic_control:
    image: naturalis/museumapp_elastic_control:latest
    environment:
      - ES_PORT=${ES_PORT}
      - ES_HOST=${ES_HOST}
      - ES_INDEX=${ES_INDEX}
      - ES_CONTROL_INDEX=${ES_CONTROL_INDEX}
      - LOGFILE_PATH=${API_LOGFILE_PATH}
    ports:
      - 5001:5000
    volumes:
      - /data:/data
    links:
      - elastic:elastic

  mysql:
    image: "mysql:5.7"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE:-reaper}
      # MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    networks:
      - default
    ports:
        - "${MYSQL_EXTERNAL_PORT:-3307}:3306"
    volumes:
      # - /data/mysql/mysqlconf:/etc/mysql/conf.d
      - /data/mysql/initdb:/docker-entrypoint-initdb.d
      - /data/mysql/db:/var/lib/mysql
      - /data/mysql/mysqllog:/var/log/mysql
      - /data/mysql/mysql-files:/var/lib/mysql-files/

  reaper:
    image: naturalis/museumapp_reaper:latest
    env_file:
      - .env
    volumes:
      - /data:/data
    links:
      - mysql:mysql

  nba_harvester:
    image: naturalis/museumapp_nba_harvester:latest
    env_file:
      - .env
    volumes:
      - /data:/data
    links:
      - mysql:mysql

  minio:
    image: minio/minio:RELEASE.2019-06-13T01-41-13Z
    restart: unless-stopped
    logging: *default-logging
    command: server /export
    environment:
      MINIO_ACCESS_KEY: ${MINIO_USER}
      MINIO_SECRET_KEY: ${MINIO_PASS}
      # MINIO_DOMAIN: s3.waarneming.ppdb.naturalis.nl
    volumes:
      - "${MINIO_DATA_DIR:-/data/minio}:/export"
    ports:
      - 9000:9000

  image_selector:
    image: naturalis/museumapp_image_selector:latest
    ports:
      - 8080:80
    volumes:
      - /data:/data
    env_file:
      - .env

  image_squares:
    image: naturalis/museumapp_image_squares:latest
    ports:
      - 8081:80
    volumes:
      - /data:/data
    env_file:
      - .env

  pipeline:
    image: naturalis/museumapp_pipeline:latest
    ports:
      - 8082:80
    volumes:
      - /data:/data
    env_file:
      - .env

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    ports:
      - 5601:5601
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    links:
      - elastic:elastic
