version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  api:
    restart: on-failure:5
    image: naturalis/museumapp_pipeline_api:1.2
    env_file:
      - .env
    logging: *default-logging
    ports:
      - 5000:5000
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.museumappapi.entrypoints=https
      - traefik.http.routers.museumappapi.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-default}
      - traefik.http.routers.museumappapi.tls=true
      - traefik.http.routers.museumappapi.rule=${API_URL_CONFIG:-Host(`museumapp.naturalis.nl`)}
    links:
      - elastic:elastic
    depends_on:
      - "bootstrap"

  api_control:
    image: naturalis/museumapp_elastic_control:1.1
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
    links:
      - elastic:elastic
    depends_on:
      - "bootstrap"

  document_loader:
    image: naturalis/museumapp_document_load:1.0
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
    links:
      - elastic:elastic
    depends_on:
      - "bootstrap"

  elastic:
    restart: on-failure:5
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    logging: *default-logging
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - "${BASE_PATH:-/data}/pipeline/es-data:/usr/share/elasticsearch/data"

  mysql:
    image: "mysql:5.7"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    logging: *default-logging
    networks:
      - default
    ports:
        - "${MYSQL_EXTERNAL_PORT:-3307}:3306"
    volumes:
      - "${BASE_PATH:-/data}/pipeline/mysql/initdb:/docker-entrypoint-initdb.d"
      - "${BASE_PATH:-/data}/pipeline/mysql/db:/var/lib/mysql"
      - "${BASE_PATH:-/data}/pipeline/mysql/mysqllog:/var/log/mysql"
      - "${BASE_PATH:-/data}/pipeline/mysql/mysql-files:/var/lib/mysql-files/"

  minio:
    image: minio/minio:RELEASE.2019-09-11T19-53-16Z
    restart: unless-stopped
    logging: *default-logging
    command: server /export
    environment:
      MINIO_ACCESS_KEY: ${MINIO_USER}
      MINIO_SECRET_KEY: ${MINIO_PASS}
    volumes:
      - "${MINIO_DATA_DIR:-/data/pipeline/minio}:/export"
    ports:
      - 9000:9000
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.museumappminio.entrypoints=https
      - traefik.http.routers.museumappminio.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-default}
      - traefik.http.routers.museumappminio.tls=true
      - traefik.http.routers.museumappminio.rule=${MINIO_URL_CONFIG:-Host(`minio-museumapp.naturalis.nl`)}

  bootstrap:
    image: naturalis/museumapp_bootstrap:1.2
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
      - "${BASE_PATH:-/data}/pipeline:/data/log"
      - "${BASE_PATH:-/data}/pipeline/leenobject_images:/data/leenobject_images"
      - "${BASE_PATH:-/data}/pipeline/stubs:/data/stubs"
      - "${BASE_PATH:-/data}/pipeline/image_selector:/data/image_selector"
      - "${BASE_PATH:-/data}/pipeline/image_squares:/data/image_squares"
      - "${BASE_PATH:-/data}/pipeline/document_hashes:/data/document_hashes"
      - "${BASE_PATH:-/data}/pipeline/management_data:/data/management_data"
      - "${BASE_PATH:-/data}/pipeline/squared_images:/data/squared_images"
      - "${BASE_PATH:-/data}/pipeline/es-data:/usr/share/elasticsearch/data"
      - "${BASE_PATH:-/data}/pipeline/documents/preview:${JSON_PREVIEW_PATH}"
      - "${BASE_PATH:-/data}/pipeline/documents/publish:${JSON_PUBLISH_PATH}"
      - "${BASE_PATH:-/data}/pipeline/documents/load:${JSON_LOAD_PATH}"
      # - "${BASE_PATH:-/data}/pipeline/export:${TRANSLATOR_EXPORT_PATH}"
    env_file:
      - .env
    logging: *default-logging
    depends_on:
      - "mysql"

  reaper:
    image: naturalis/museumapp_reaper:1.3
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
    links:
      - mysql:mysql

  nba_harvester:
    image: naturalis/museumapp_nba_harvester:1.3
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
    links:
      - mysql:mysql

  crs_harvester:
    image: naturalis/museumapp_crs_harvester:1.1
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
    logging: *default-logging
    env_file:
      - .env
    links:
      - mysql:mysql

  square_maker:
    image: naturalis/museumapp_image_square_maker:1.0
    volumes:
      - "${BASE_PATH:-/data}/pipeline/image_squares:/data/image_squares"
      - "${BASE_PATH:-/data}/pipeline/squared_images:/data/squared_images"
    logging: *default-logging
    env_file:
      - .env

  pipeline:
    image: naturalis/museumapp_pipeline:1.5
    ports:
      - 8090:80
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
      - "${BASE_PATH:-/data}/pipeline/documents:/data/documents"
      - "${BASE_PATH:-/data}/pipeline/log:/data/log"
      - "${BASE_PATH:-/data}/pipeline/queue:/data/queue"
    env_file:
      - .env
    logging: *default-logging
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.museumappipeline.entrypoints=https
      - traefik.http.routers.museumappipeline.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-default}
      - traefik.http.routers.museumappipeline.tls=true
      - traefik.http.routers.museumappipeline.rule=${PIPELINE_URL_CONFIG:-Host(`pipeline-museumapp.naturalis.nl`)}
    depends_on:
      - "bootstrap"

  image_selector:
    image: naturalis/museumapp_image_selector:1.1
    ports:
      - 8091:80
    volumes:
      - "${BASE_PATH:-/data}/pipeline/image_selector:/data/image_selector"
    logging: *default-logging
    env_file:
      - .env
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.museumappselector.entrypoints=https
      - traefik.http.routers.museumappselector.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-default}
      - traefik.http.routers.museumappselector.tls=true
      - traefik.http.routers.museumappselector.rule=${SELECTOR_URL_CONFIG:-Host(`selector-museumapp.naturalis.nl`)}
    depends_on:
      - "bootstrap"

  image_squares:
    image: naturalis/museumapp_image_squares:1.1
    ports:
      - 8092:80
    volumes:
      - "${BASE_PATH:-/data}/pipeline/image_squares:/data/image_squares"
    env_file:
      - .env
    logging: *default-logging
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.museumappsquares.entrypoints=https
      - traefik.http.routers.museumappsquares.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-default}
      - traefik.http.routers.museumappsquares.tls=true
      - traefik.http.routers.museumappsquares.rule=${SQUARES_URL_CONFIG:-Host(`squares-museumapp.naturalis.nl`)}
    depends_on:
      - "bootstrap"

  translator:
    image: naturalis/museumapp_translator:1.1
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
    env_file:
      - .env
    logging: *default-logging
    depends_on:
      - "bootstrap"

  traefik:
    image: traefik:2.0.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - default
      - web
    logging: *default-logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik

networks:
  web:
    external: true
