version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  api:
    restart: on-failure:5
    image: naturalis/museumapp_pipeline_api:1.0
    env_file:
      - .env
    logging: *default-logging
    ports:
      - 5000:5000
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
    labels:
      - "traefik.backend=museumapp-api"
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "${API_URL_CONFIG:-traefik.frontend.rule=Host:museumapp.naturalis.nl}"
    links:
      - elastic:elastic
    depends_on:
      - "bootstrap"

  api_control:
    image: naturalis/museumapp_elastic_control:1.0
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
    links:
      - elastic:elastic
    depends_on:
      - "bootstrap"

  document_loader:
    image: naturalis/museumapp_document_load:1.0
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
    links:
      - elastic:elastic
    depends_on:
      - "bootstrap"

  elastic:
    restart: on-failure:5
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    logging: *default-logging
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - "${BASE_PATH:-/data}/pipeline/es-data:/usr/share/elasticsearch/data"

  mysql:
    image: "mysql:5.7"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    logging: *default-logging
    networks:
      - default
    ports:
        - "${MYSQL_EXTERNAL_PORT:-3307}:3306"
    volumes:
      - "${BASE_PATH:-/data}/pipeline/mysql/initdb:/docker-entrypoint-initdb.d"
      - "${BASE_PATH:-/data}/pipeline/mysql/db:/var/lib/mysql"
      - "${BASE_PATH:-/data}/pipeline/mysql/mysqllog:/var/log/mysql"
      - "${BASE_PATH:-/data}/pipeline/mysql/mysql-files:/var/lib/mysql-files/"

  minio:
    #image: minio/minio:RELEASE.2019-06-13T01-41-13Z
    image: minio/minio:RELEASE.2019-09-11T19-53-16Z
    restart: unless-stopped
    logging: *default-logging
    command: server /export
    environment:
      MINIO_ACCESS_KEY: ${MINIO_USER}
      MINIO_SECRET_KEY: ${MINIO_PASS}
    volumes:
      - "${MINIO_DATA_DIR:-/data/pipeline/minio}:/export"
    ports:
      - 9000:9000
    labels:
      - "traefik.backend=museumapp-minio"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "${MINIO_URL_CONFIG:-traefik.frontend.rule=Host:minio-museumapp.naturalis.nl}"

  bootstrap:
    image: naturalis/museumapp_bootstrap:1.0
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
      - "${BASE_PATH:-/data}/pipeline:/data/log"
      - "${BASE_PATH:-/data}/pipeline/leenobject_images:/data/leenobject_images"
      - "${BASE_PATH:-/data}/pipeline/stubs:/data/stubs"
      - "${BASE_PATH:-/data}/pipeline/image_selector:/data/image_selector"
      - "${BASE_PATH:-/data}/pipeline/image_squares:/data/image_squares"
      - "${BASE_PATH:-/data}/pipeline/document_hashes:/data/document_hashes"
      - "${BASE_PATH:-/data}/pipeline/management_data:/data/management_data"
      - "${BASE_PATH:-/data}/pipeline/squared_images:/data/squared_images"
      - "${BASE_PATH:-/data}/pipeline/es-data:/usr/share/elasticsearch/data"
      - "${BASE_PATH:-/data}/pipeline/documents/preview:${JSON_PREVIEW_PATH}"
      - "${BASE_PATH:-/data}/pipeline/documents/publish:${JSON_PUBLISH_PATH}"
      - "${BASE_PATH:-/data}/pipeline/documents/load:${JSON_LOAD_PATH}"
    env_file:
      - .env
    logging: *default-logging
    depends_on:
      - "mysql"

  reaper:
    image: naturalis/museumapp_reaper:1.0
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
    links:
      - mysql:mysql

  nba_harvester:
    image: naturalis/museumapp_nba_harvester:1.0
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
    links:
      - mysql:mysql

  crs_harvester:
    image: naturalis/museumapp_crs_harvester:1.0
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
    logging: *default-logging
    env_file:
      - .env
    links:
      - mysql:mysql

  square_maker:
    image: naturalis/museumapp_image_square_maker:1.0
    volumes:
      - "${BASE_PATH:-/data}/pipeline/image_squares:/data/image_squares"
      - "${BASE_PATH:-/data}/pipeline/squared_images:/data/squared_images"
    logging: *default-logging
    env_file:
      - .env

  pipeline:
    image: naturalis/museumapp_pipeline:1.0
    ports:
      - 8090:80
    volumes:
      - "${BASE_PATH:-/data}/pipeline:/data"
      - "${BASE_PATH:-/data}/pipeline/documents:/data/documents"
      - "${BASE_PATH:-/data}/pipeline/log:/data/log"
      - "${BASE_PATH:-/data}/pipeline/queue:/data/queue"
    env_file:
      - .env
    logging: *default-logging
    labels:
      - "traefik.backend=museumapp-pipeline"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "${PIPELINE_URL_CONFIG:-traefik.frontend.rule=Host:pipeline_museumapp.naturalis.nl}"
    depends_on:
      - "bootstrap"

  image_selector:
    image: naturalis/museumapp_image_selector:1.0
    ports:
      - 8091:80
    volumes:
      - "${BASE_PATH:-/data}/pipeline/image_selector:/data/image_selector"
    logging: *default-logging
    env_file:
      - .env
    labels:
      - "traefik.backend=museumapp-selector"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "${SELECTOR_URL_CONFIG:-traefik.frontend.rule=Host:selector_museumapp.naturalis.nl}"
    depends_on:
      - "bootstrap"

  image_squares:
    image: naturalis/museumapp_image_squares:1.0
    ports:
      - 8092:80
    volumes:
      - "${BASE_PATH:-/data}/pipeline/image_squares:/data/image_squares"
    env_file:
      - .env
    logging: *default-logging
    labels:
      - "traefik.backend=museumapp-squares"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "${SQUARES_URL_CONFIG:-traefik.frontend.rule=Host:squares_museumapp.naturalis.nl}"
    depends_on:
      - "bootstrap"

  traefik:
    image: traefik:1.7.14
    restart: unless-stopped
    environment:
      - TRANSIP_PRIVATE_KEY_PATH=/.transip.key
      - TRANSIP_ACCOUNT_NAME=${TRANSIP_ACCOUNT_NAME:-naturalis}
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - web
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE:-./traefik.toml}:/traefik.toml
      - ${ACME_JSON:-./acme.json}:/acme.json
      - ./.transip.key:/.transip.key
    logging: *default-logging

  # kibana:
  #   image: docker.elastic.co/kibana/kibana-oss:7.2.0
  #   ports:
  #     - 5601:5601
  #   # volumes:
  #   #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  #   environment:
  #     ELASTICSEARCH_HOSTS: http://elastic:9200
  #   links:
  #     - elastic:elastic

networks:
  web:
    external: true
