[Global]
  checkNewVersion = true
  sendAnonymousUsage = false

[log]
  level = "INFO"

[entrypoints]
  [entrypoints.http]
  address = ":80"

  [entrypoints.https]
  address = ":443"

[api]
  dashboard = true
  debug = false
  insecure = true

[certificatesResolvers.default.acme]
  email = "your-email@your-domain.org"
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.sample.acme.httpChallenge]
    # used during the challenge
    entryPoint = "http"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedbydefault = false
  [providers.file]
    filename = "/etc/traefik/dynamic-conf.toml"
