#!/bin/bash

CRON_LOG=$(grep CRON_LOG ../.env | cut -d '=' -f2,3)
LEENOBJECTEN_PATH_INCOMING_HOST=$(grep LEENOBJECTEN_PATH_INCOMING_HOST ../.env | cut -d '=' -f2,3)
LEENOBJECTEN_PATH_MEDIA_HOST=$(grep LEENOBJECTEN_PATH_MEDIA_HOST ../.env | cut -d '=' -f2,3)

if [ ! -d "$LEENOBJECTEN_PATH_MEDIA_HOST" ]; then
    mkdir $LEENOBJECTEN_PATH_MEDIA_HOST
fi

mv $LEENOBJECTEN_PATH_INCOMING_HOST/* $LEENOBJECTEN_PATH_MEDIA_HOST
